<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="josh-Latitude-3410" failures="2" tests="20" name="testcases.Droppable_Test" time="3.087" errors="0" timestamp="2023-01-24T10:22:02 IST" skipped="0">
  <testcase classname="testcases.Droppable_Test" name="navigate_to_droppable" time="0.192"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="simple_drag_drop" time="0.348"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_simple_drop_successful" time="0.019"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="switch_to_accept_tab" time="0.110"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="not_acceptable_drop" time="0.328"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_drag_not_accepted" time="0.021"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="acceptable_drop" time="0.303"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_drag_accepted" time="0.030"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="switch_to_prevent_propagation_tab" time="0.076"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="greedy_inner_drag_drop" time="0.322"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_greedy_inner_text" time="0.067">
    <failure message="expected [Dropped!] but found [Inner droppable (greedy)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Dropped!] but found [Inner droppable (greedy)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at base.Base.verify_text(Base.java:80)
at actions.Droppable.verify_greedy_inner_text(Droppable.java:72)
at testcases.Droppable_Test.verify_greedy_inner_text(Droppable_Test.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_greedy_inner_text -->
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_greedy_outer_text" time="0.025"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="not_greedy_inner_drop" time="0.320"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_not_greedy_inner_text" time="0.034"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_not_greedy_outer_text" time="0.026"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="switch_to_Revert_Draggable_tab" time="0.069"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="revertable_Drag_Drop" time="0.438"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_revertable_drag_successful" time="0.001">
    <failure message="expected [(700, 348)] but found [(451, 302)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [(700, 348)] but found [(451, 302)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at actions.Droppable.verify_revertable_drag_location(Droppable.java:118)
at testcases.Droppable_Test.verify_revertable_drag_successful(Droppable_Test.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_revertable_drag_successful -->
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="not_revertable_Drag_Drop" time="0.355"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_not_revertable_drag_successful" time="0.003"/>
  <system-out/>
</testsuite> <!-- testcases.Droppable_Test -->
